### ISSUE TITLE
Multiple Shade Cloak dash

### ISSUE THREAD

**Issue by Araraura** [flibber-hk/HollowKnight.SkillUpgrades#1]
Can you add a skill that gives you more shade cloak dashes? Like being able to shade cloak twice in a row before it having to recharge or something (maybe an option for infinite shade cloaks in settings, even if it is pretty cheaty)

**Comment by flibber-hk** [comment]
I think faster shade cloak recharge doesn't really fit in this mod (I think I prefer having things which are a bit more substantial change in terms of implementation). If you wanted to change the shadow dash recharge time it's enough to just change the `SHADOW_DASH_COOLDOWN` float in the HeroController class - for instance, the code

```
On.HeroController.Start += (orig, self) => { orig(self); self.SHADOW_DASH_COOLDOWN = 0.1f; };
```
or something like that.
